/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Lucy(props) {
  const { nodes, materials } = useGLTF("./models/lucy.gltf");

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lucy001.geometry}>
        <meshPhysicalMaterial {...props} />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/lucy.gltf");
